### ISSUE TITLE
Add links to user profile socials

### ISSUE THREAD

**Issue by esot321c** [ergopad/ergopad-api#540]

**Comment by michaelmirandi** [comment]
When clicking on a user social link, a new window will open up with the corresponding profile

- [x] Reddit
- [x] Youtube
- [x] Telegram
- [x] Twitter
- [x] Discord
- [x] Medium
- [x] Github
- [x] Facebook
- [x] Instagram

**Comment by michaelmirandi** [comment]
Completed, have in the dynamic-dao branch. Need to finish theming & dao membership check. Moving forward, I'll create a branch for each issue to remove unnecessary dependencies
