### ISSUE TITLE
Optimize Paideia images

### ISSUE THREAD

**Issue by esot321c** [ergopad/ergopad-api#574]
User profile images are not optimized on the backend. They load the full size image, even when displayed at 81x81 px. 

Could we optimize during upload to S3 to the max image size expected? Can also optimize in next/image further for each different size.

**Comment by noob77777** [comment]
## Solution:
The current file upload endpoint is a generalised endpoint that accepts all files. We will have an endpoint dedicated to image upload. `/util/upload_image/{image_type}`.
We can have `image_type` as the following (values in px)
```
{
    "xs": 40,
     "s": 120,
     "m": 240,
     "l": 720,
     "original": None
}
```

The smaller side of the image will be resized to the config. For example if a `1080x1920` image is uploaded as `"m"`. The resulting image will be `240*427`

We can use python's `Pillow` module for this.

**Comment by esot321c** [comment]
great solution. how does it deal with aspect ratio? in your example what if the image was 1920x1080 instead, would it be 427*240?  the smaller of the two meets the minimum?

**Comment by noob77777** [comment]
> great solution. how does it deal with aspect ratio? in your example what if the image was 1920x1080 instead, would it be 427*240? the smaller of the two meets the minimum?

yes

**Comment by esot321c** [comment]
Actually, in my testing it shortens the _long_ side to match the compression value
