### ISSUE TITLE
Handle DAO membership

### ISSUE THREAD

**Issue by vikingphoenix** [ergopad/ergopad-api#583]
Make generic version of 
https://github.com/ergo-pad/danaides/pull/60/files#top

Allow multiple tokens in single request.

**Comment by vikingphoenix** [comment]
this calls api/token/locked for each address, currently

**Comment by noob77777** [comment]
Done: https://github.com/ergo-pad/paideia-api/pull/49

**Comment by noob77777** [comment]
> this calls api/token/locked for each address, currently

This endpoint is broken after last update. @vikingphoenix

**Comment by vikingphoenix** [comment]
@noob77777 do you need this endpoint anymore since you can call membership endpoint?

**Comment by noob77777** [comment]
It was already being used to check token balances. Its nice to have both
