### ISSUE TITLE
Paideia-state api spec

### ISSUE THREAD

**Issue by Luivatra** [ergopad/ergopad-api#603]
Paideia state will handle interaction with paideia contracts. It exposes an API and keeps track of the current state of all DAO's in Paideia

**Comment by esot321c** [comment]
Once we are connecting to smart contracts between Paideia SDK and Paideia API, look here

**Comment by esot321c** [comment]
- User Facing endpoints are GET typically
- If user wants to stake, for example, SDK provides unsigned tx as a response (should be fairly straightforward)
