### ISSUE TITLE
Error when a user was logged out due to JWT timeout should say "Timed out, please login again" and give them the prompt to do so

### ISSUE THREAD

**Issue by esot321c** [ergopad/ergopad-api#620]

**Comment by esot321c** [comment]
Error message appears when adding comments
does not work when creating a discussion

- review tasks a user can do to check if the error comes up
- make error message more verbose so the user knows what action they must take to resolve it (log back in)

it could even bring up the window which lets them log back in, instead of just telling them about it

**Comment by noob77777** [comment]
Tracking pending issues in: https://github.com/ergopad/ergopad-api/issues/615
