### ISSUE TITLE
When a proposal/discussion is referenced and gets deleted, the reference remains with a bad link

### ISSUE THREAD

**Issue by esot321c** [ergopad/ergopad-api#623]
Options: 

- Reference remains visible, but it displays "Deleted" somehow
- Reference is removed completely
- Proposals that have been referenced are cached, but removed from the list of active proposals and only show up as a link where another proposal references them.

**Comment by esot321c** [comment]
Example: 

https://app.paideia.im/paideia/discussion/once-upon-a-time-10?tab=referenced

**Comment by noob77777** [comment]
Can you paste the output for the following in prod db.
```
\d proposal_references;
```

**Comment by noob77777** [comment]
The example proposal reference is not deleted. The issue is the page redirects to `/discussion/1` instead of `paideia/discussion/hello-paideia-1`
